
export enum GamePhase {
  INTRO = 'INTRO',
  MISSION_1 = 'MISSION_1',
  MISSION_2 = 'MISSION_2',
  KNOWLEDGE = 'KNOWLEDGE',
  FINAL_MISSION = 'FINAL_MISSION',
  DEBRIEFING = 'DEBRIEFING',
  END = 'END',
}
